trigger:
  - main

variables:
- group: FOO

steps:
  - script: |
      echo 'first pipeline'
      echo '$(Build.Repository.ID)'
      commitID=$(git rev-parse --short HEAD)
      echo $commitID 
    displayName: First
  
  - script: |
      mkdir builder
      echo 'Candidate tag: $(CANDIDATED_TAG)'
      echo 'Build Number: $(Build.BuildNumber)'
      echo 'artifact-$(Build.BuildNumber)' > builder/buildVersion1
      echo 'tag-$(Build.BuildNumber)' > builder/buildVersion2
    displayName: Echo Group Variables
    
  # - task: PublishBuildArtifacts@1
  #   inputs:
  #     PathtoPublish: '$(System.DefaultWorkingDirectory)/buildVersion'
  #     ArtifactName: 'build'
  #     publishLocation: 'Container'

  - publish: $(System.DefaultWorkingDirectory)/builder
    artifact: build
