trigger:
  - main

variables:
- group: FOO

steps:
  - script: |
      echo 'first pipeline'
    displayName: First
  
  - script: |
      echo $(CANDIDATED_TAG)
    displayName: Echo Group Variables
