trigger:
  - main

variables:
- group: FOO

steps:
  - script: |
      echo 'first pipeline'
    displayName: First
  
  - script: |
      echo 'Candidate tag: $(CANDIDATED_TAG)'
      echo 'Build Number: $(Build.BuildNumber)'
      echo '$(Build.BuildNumber)' > buildVersion
    displayName: Echo Group Variables


  - publish: $(System.DefaultWorkingDirectory)/buildVersion
    artifact: build
